const products = [
  {
    name: "Dried Carrot",
    category: "Vegetables",
    price: 320,
    stock: false,
    image: "images/1.png",
  },
  {
    name: "Dried Beetroot",
    category: "Vegetables",
    price: 340,
    stock: false,
    image: "images/1.png",
  },
  {
    name: "Dried Tomato",
    category: "Vegetables",
    price: 420,
    stock: true,
    image: "images/1.png",
  },
  {
    name: "Dried Pumpkin",
    category: "Vegetables",
    price: 380,
    stock: true,
    image: "images/1.png",
  },
  {
    name: "Dried Banana Chips",
    category: "Fruits",
    price: 299,
    stock: true,
    image: "images/1.png",
  },
  {
    name: "Dried Apple Slices",
    category: "Fruits",
    price: 399,
    stock: false,
    image: "images/1.png",
  },
  {
    name: "Dried Mango",
    category: "Fruits",
    price: 499,
    stock: true,
    image: "images/1.png",
  },
  {
    name: "Dried Papaya",
    category: "Fruits",
    price: 450,
    stock: false,
    image: "images/1.png",
  },
  {
    name: "Dried Pineapple",
    category: "Fruits",
    price: 550,
    stock: true,
    image: "images/1.png",
  },
  {
    name: "Dried Kiwi",
    category: "Fruits",
    price: 600,
    stock: false,
    image: "images/1.png",
  },
  {
    name: "Dried Strawberry",
    category: "Fruits",
    price: 699,
    stock: true,
    image: "images/1.png",
  },
  {
    name: "Dried Blueberry",
    category: "Fruits",
    price: 850,
    stock: true,
    image: "images/1.png",
  },
  {
    name: "Dried Cranberry",
    category: "Fruits",
    price: 750,
    stock: false,
    image: "images/1.png",
  },
  {
    name: "Dried Dates",
    category: "Fruits",
    price: 499,
    stock: true,
    image: "images/1.png",
  },
  {
    name: "Strawberry Pieces",
    category: "Fruits",
    price: 699,
    stock: false,
    image: "images/1.png",
  },
  {
    name: "Dried Green Peas",
    category: "Vegetables",
    price: 360,
    stock: true,
    image: "images/1.png",
  },
  {
    name: "Dried Broccoli",
    category: "Vegetables",
    price: 450,
    stock: false,
    image: "images/1.png",
  },
  {
    name: "Dried Spinach",
    category: "Vegetables",
    price: 400,
    stock: true,
    image: "images/1.png",
  },
  {
    name: "Dried Cauliflower",
    category: "Vegetables",
    price: 390,
    stock: true,
    image: "images/1.png",
  },
  {
    name: "Dried Mushroom",
    category: "Vegetables",
    price: 500,
    stock: true,
    image: "images/1.png",
  },
];
export default products;
